dubbo:
  protocol:
    name: tri
    port: -1
  registry:
#    nacos需开放9984端口：grpc协议
    address: nacos://${spring.cloud.nacos.server-addr:112.124.23.224:8848}
    group: dubbo
spring:
  application:
    name: dubbo-example-rest-api
  profiles:
    active: dev
#  cloud:
#    nacos:
#      server-addr: 112.124.23.224:8848
#      discovery:
#        group: restful-api
server:
  port: 8080
logging:
  config: classpath:log4j2-${spring.profiles.active}.xml
#  config: http://${spring.cloud.nacos.server-addr}/nacos/v1/cs/configs?group=micro-service&tenant=public&dataId=log4j2.xml